version: '3.8'
services:
  mongodb:
    image: leaffyearthdocker/mongo:latest
    container_name: leaffy-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  backend:
    image: leaffyearthdocker/leaffy-infra-backend:latest
    container_name: my-backend
    ports:
      - "5000:3000"  # Backend now listens on 5000
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/leaffyearth
      GOOGLE_CALLBACK_URL: https://portal.leaffyearth.com/auth/google/callback
      GOOGLE_REDIRECT_URI: https://portal.leaffyearth.com/auth/google/callback
      ADMIN_CONSOLE_URL: https://portal.leaffyearth.com
    networks:
      - app-network
  frontend:
    image: leaffyearthdocker/leaffy-infra-frontend:latest
    container_name: my-frontend
    ports:
      - "3002:5000"  # Frontend now listens on 3002
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - GOOGLE_CLIENT_ID=1036536798555-70r67fripu8qi4p9g7utrv6nus6llne8.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - NEXTAUTH_URL=https://portal.leaffyearth.com
      - NEXTAUTH_SECRET=passleaffyearth # Generate with: openssl rand -base64 32
      - NEXT_PUBLIC_API_URL=http://backend:5000
      - NEXT_PUBLIC_APP_URL=https://portal.leaffyearth.com
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
