services:
  mongodb:
    image: leaffyearthdocker/mongo:latest
    container_name: leaffy-mongo
    ports:
      - "27019:27017"  # Expose MongoDB on port 27018 (local) -> 27017 (container)
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped 

  backend:
    build:
      context: ../../leaffyearth  # Root of the monorepo
      dockerfile: infra/backend/Dockerfile
    ports:
      - "3000:3000"
    container_name: my-backend
    restart: unless-stopped
    depends_on:
      - mongodb  # Ensures MongoDB starts first
    environment:
      MONGODB_URI: mongodb://mongodb:27017/leaffyearth  # Use service name "mongodb", NOT localhost
      GOOGLE_CALLBACK_URL: "http://localhost:3000/auth/google/callback"
    networks:
      - app-network

  frontend:
    build:
      context: ../../leaffyearth  # Root of the monorepo
      dockerfile: infra/frontend/Dockerfile
    ports:
      - "5000:5000"  # Expose frontend on port 5000 (local) -> 3000 (container)      
    container_name: my-frontend
    restart: unless-stopped
    depends_on:
      - backend  # Ensure backend starts before frontend
    networks:
      - app-network
    environment:
      - NEXT_PUBLIC_API_SERVER_BASE_URL=http://localhost:3000  # Point Next.js frontend to backend inside Docker
      - GOOGLE_CLIENT_ID=1036536798555-70r67fripu8qi4p9g7utrv6nus6llne8.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - NEXTAUTH_URL=http://localhost:5000
      - NEXTAUTH_SECRET=passleaffyearth # Generate with: openssl rand -base64 32 
      - NEXT_PUBLIC_API_URL=http://backend:3000
      - NEXT_PUBLIC_APP_URL=http://localhost:5000

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
