name: Caching-test
on:
  push:
    branches: ['SandBox']

jobs:
  download-and-cache:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'gsutil'

      - name: Download 5 GB artifact from GCS and measure speed
        id: timed-download
        run: |
          # CONFIGURATION
          FILE="bigtest.img"
          BUCKET="monkci-gha-runner-cache"
          DEST="bin/"

          echo "🚀 Downloading '$FILE' to gs://$BUCKET/${DEST}${FILE}..."

          # TIME DOWNLOAD
          START=$(date +%s.%N)
          gcloud storage cp gs://$BUCKET/${DEST}${FILE} .
          END=$(date +%s.%N)

          # GET FILE SIZE
          FILESIZE_BYTES=$(stat --format=%s "$FILE" 2>/dev/null || stat -f%z "$FILE")
          FILESIZE_MB=$(awk "BEGIN {printf \"%.2f\", $FILESIZE_BYTES/1024/1024}")
          FILESIZE_Gb=$(awk "BEGIN {printf \"%.2f\", ($FILESIZE_BYTES * 8) / (1024*1024*1024)}")

          # CALCULATE TIME + SPEED
          ELAPSED=$(awk "BEGIN {printf \"%.3f\", $END - $START}")
          SPEED_Gbps=$(awk "BEGIN {printf \"%.3f\", ($FILESIZE_BYTES * 8) / (1024*1024*1024) / $ELAPSED}")

          echo ""
          echo "✅ Download completed."
          echo "📦 Size: ${FILESIZE_Gb} Gb"
          echo "⏱  Time taken: ${ELAPSED} seconds"
          echo "⚡ Speed: ${SPEED_Gbps} Gbps"
