name: Geekbench Benchmark

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  benchmark:
    # every job runs on the same ubuntu‑latest runner
    runs-on: ubuntu-latest

    # ── matrix of primitive strings ──
    strategy:
      matrix:
        label: [ "ubuntu-latest", "ubuntu-latest", "ubuntu-latest", "ubuntu-latest", "ubuntu-latest", "ubuntu-latest", "ubuntu-latest", "ubuntu-latest" ]

    name: Geekbench – ${{ matrix.label }}

    steps:
      - uses: actions/checkout@v4

      - name: Download Geekbench
        run: |
          curl -sSL -o Geekbench-6.tar.gz \
            https://cdn.geekbench.com/Geekbench-6.4.0-Linux.tar.gz
          tar -xzf Geekbench-6.tar.gz
          mv Geekbench-6.4.0-Linux geekbench

      - name: Run Geekbench CPU benchmark
        id: run
        run: |
          ./geekbench/geekbench_x86_64 --cpu | tee geekbench.log

      - name: Extract scores
        id: scores
        run: |
          SINGLE=$(grep -m1 "Single-Core Score" geekbench.log | awk '{print $NF}')
          MULTI=$(grep -m1 "Multi-Core Score"  geekbench.log | awk '{print $NF}')
          echo "single=$SINGLE" >> $GITHUB_OUTPUT
          echo "multi=$MULTI"  >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: geekbench-log-${{ matrix.label }}
          path: geekbench.log

      - name: Add summary
        run: |
          echo "## Geekbench 6.4 – ${{ matrix.label }}"           >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Score |"                               >> $GITHUB_STEP_SUMMARY
          echo "|--------|-------|"                               >> $GITHUB_STEP_SUMMARY
          echo "| Single‑Core | **${{ steps.scores.outputs.single }}** |" >> $GITHUB_STEP_SUMMARY
          echo "| Multi‑Core  | **${{ steps.scores.outputs.multi }}** |"  >> $GITHUB_STEP_SUMMARY
