name: Advanced Benchmark with Phoronix

on:
  workflow_dispatch:

jobs:
  run-phoronix:
    runs-on: ubuntu-latest

    steps:
      - name: Install Phoronix Test Suite
        run: |
          # Download and install the suite
          wget https://phoronix-test-suite.com/releases/phoronix-test-suite-10.8.4.tar.gz
          tar -xf phoronix-test-suite-10.8.4.tar.gz
          cd phoronix-test-suite/

      - name: Run a CPU Benchmark (Stress-NG)
        # This will auto-download and run the 'Stress-NG' test for the CPU
        run: |
          cd phoronix-test-suite/
          export DEBIAN_FRONTEND=noninteractive
          # The 'batch-run' command is for non-interactive execution
          ./phoronix-test-suite batch-run pts/stress-ng
