name: Advanced Benchmark with Phoronix

on:
  push:
    branches: [ master ]
jobs:
  run-phoronix:
    runs-on: ubuntu-latest

    steps:
      - name: Install Phoronix Test Suite
        run: |
          # Download and install the suite
          wget https://phoronix-test-suite.com/releases/phoronix-test-suite-10.8.4.tar.gz
          tar -xf phoronix-test-suite-10.8.4.tar.gz
          cd phoronix-test-suite/

      - name: Run a CPU Benchmark (Stress-NG)
        run: |
          cd phoronix-test-suite/
          export DEBIAN_FRONTEND=noninteractive
          
          # First, run batch-setup for non-interactive configuration
          ./phoronix-test-suite batch-setup
          
          # Now, run the actual benchmark using batch-run
          ./phoronix-test-suite batch-run pts/stress-ng
        env:
          # Optional: Add these environment variables to upload results
          UPLOAD_RESULTS: 1
          ANONYMOUS_LOGIN: 1
