name: CPU Benchmark Test

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  run-passmark-benchmark:
    runs-on: ubuntu-22.04     # pin to jammy

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip libncurses5

      - name: Download PassMark Tool
        run: wget https://www.passmark.com/downloads/PerformanceTest_Linux_x86-64.zip -O pt_linux.zip

      - name: Unzip Tool
        run: unzip pt_linux.zip

      - name: Run CPU Benchmark
        run: |
          cd PerformanceTest
          chmod +x pt_linux_x64
          ./pt_linux_x64 -c
