name: Node.js CI with Caching

on:
  push:
    branches: ['master']
  pull_request:

jobs:
  debug:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH debug session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 130
